"""initial

Revision ID: 50168788b091
Revises: 
Create Date: 2022-03-22 12:36:55.778091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50168788b091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kecamatan',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pelajaran',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kode', sa.String(length=255), nullable=True),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('ujian',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jadwal_ujian',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ujian_id', sa.String(length=36), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('sesi', sa.String(length=100), nullable=True),
    sa.Column('tanggal', sa.DateTime(), nullable=True),
    sa.Column('durasi', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pelajaran_ujian',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ujian_id', sa.String(length=36), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pertanyaan',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('pertanyaan', sa.Text(), nullable=True),
    sa.Column('jumlah_pilihan', sa.Integer(), nullable=True),
    sa.Column('tipe_pertanyaan', sa.String(length=50), nullable=True),
    sa.Column('pilihan_a', sa.String(length=255), nullable=True),
    sa.Column('pilihan_b', sa.String(length=255), nullable=True),
    sa.Column('pilihan_c', sa.String(length=255), nullable=True),
    sa.Column('pilihan_d', sa.String(length=255), nullable=True),
    sa.Column('pilihan_e', sa.String(length=255), nullable=True),
    sa.Column('jawaban', sa.String(length=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sekolah',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('npsn', sa.String(length=100), nullable=True),
    sa.Column('kecamatan_id', sa.String(length=10), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kepala_sekolah', sa.String(length=100), nullable=True),
    sa.Column('no_hp_kepala_sekolah', sa.String(length=20), nullable=True),
    sa.Column('nip_kepala_sekolah', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['kecamatan_id'], ['kecamatan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rombongan_belajar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('tingkat_pendidikan', sa.String(length=2), nullable=True),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ujian_sekolah',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ujian_id', sa.String(length=36), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('jadwal_ujian_id', sa.String(length=36), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('kode', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_ujian_id'], ['jadwal_ujian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('nama', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('nis', sa.String(length=100), nullable=True),
    sa.Column('nik', sa.String(length=100), nullable=True),
    sa.Column('ibu', sa.String(length=255), nullable=True),
    sa.Column('ayah', sa.String(length=255), nullable=True),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=1), nullable=True),
    sa.Column('rombongan_belajar_id', sa.String(length=36), nullable=True),
    sa.Column('tempat_lahir', sa.String(length=255), nullable=True),
    sa.Column('tanggal_lahir', sa.DateTime(timezone=True), nullable=True),
    sa.Column('no_hp', sa.String(length=20), nullable=True),
    sa.Column('nip', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['rombongan_belajar_id'], ['rombongan_belajar.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ujian_peserta',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ujian_id', sa.String(length=36), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('jadwal_ujian_id', sa.String(length=36), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('hasil', sa.Float(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=True),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_ujian_id'], ['jadwal_ujian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jawaban',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ujian_id', sa.String(length=36), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('jadwal_ujian_id', sa.String(length=36), nullable=True),
    sa.Column('sekolah_id', sa.String(length=36), nullable=True),
    sa.Column('ujian_peserta_id', sa.String(length=36), nullable=True),
    sa.Column('pertanyaan_id', sa.String(length=36), nullable=True),
    sa.Column('jawaban', sa.String(length=1), nullable=True),
    sa.Column('benar', sa.Boolean(), nullable=True),
    sa.Column('nomor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jadwal_ujian_id'], ['jadwal_ujian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pertanyaan_id'], ['pertanyaan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sekolah_id'], ['sekolah.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_id'], ['ujian.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ujian_peserta_id'], ['ujian_peserta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jawaban')
    op.drop_table('ujian_peserta')
    op.drop_table('user')
    op.drop_table('ujian_sekolah')
    op.drop_table('rombongan_belajar')
    op.drop_table('sekolah')
    op.drop_table('pertanyaan')
    op.drop_table('pelajaran_ujian')
    op.drop_table('jadwal_ujian')
    op.drop_table('ujian')
    op.drop_table('pelajaran')
    op.drop_table('kecamatan')
    # ### end Alembic commands ###
