"""empty message

Revision ID: 6f7751f47a7c
Revises: afc8745b0ee5
Create Date: 2022-03-29 02:54:15.061423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f7751f47a7c'
down_revision = 'afc8745b0ee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'user', ['username'], unique=False)
    # ### end Alembic commands ###
