"""empty message

Revision ID: afc8745b0ee5
Revises: b1fc3a15e0f9
Create Date: 2022-03-29 01:05:01.945968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc8745b0ee5'
down_revision = 'b1fc3a15e0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('latest_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config')
    # ### end Alembic commands ###
