"""remove unique in pelajaran

Revision ID: b1fc3a15e0f9
Revises: c415c97d8a9e
Create Date: 2022-03-27 11:32:26.510593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1fc3a15e0f9'
down_revision = 'c415c97d8a9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('kode', table_name='pelajaran')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('kode', 'pelajaran', ['kode'], unique=False)
    # ### end Alembic commands ###
