from os import environ

SECRET_KEY = environ.get("SECRET_KEY")

SQLALCHEMY_DATABASE_URI = environ.get("SQLALCHEMY_DATABASE_URI")
SQLALCHEMY_TRACK_MODIFICATIONS = False

SERVER_CENTRAL_URL = environ.get("SERVER_CENTRAL_URL")
SERVER_LOCAL_URL = environ.get("SERVER_LOCAL_URL")
