"""add created date

Revision ID: 7657caa16b02
Revises: 50168788b091
Create Date: 2022-03-24 23:16:49.820895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7657caa16b02'
down_revision = '50168788b091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jawaban', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('jawaban', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pelajaran_ujian', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('pelajaran_ujian', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ujian', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('ujian', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ujian_peserta', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('ujian_peserta', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ujian_sekolah', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('ujian_sekolah', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ujian_sekolah', 'updated_at')
    op.drop_column('ujian_sekolah', 'created_at')
    op.drop_column('ujian_peserta', 'updated_at')
    op.drop_column('ujian_peserta', 'created_at')
    op.drop_column('ujian', 'updated_at')
    op.drop_column('ujian', 'created_at')
    op.drop_column('pelajaran_ujian', 'updated_at')
    op.drop_column('pelajaran_ujian', 'created_at')
    op.drop_column('jawaban', 'updated_at')
    op.drop_column('jawaban', 'created_at')
    # ### end Alembic commands ###
