"""jawaban to text

Revision ID: 9e60aadc8f3d
Revises: f7ac547b1826
Create Date: 2022-03-31 11:05:09.999568

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e60aadc8f3d'
down_revision = 'f7ac547b1826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('gambar', 'data_gambar',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=1500000),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_a',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_b',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_c',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_d',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_e',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pertanyaan', 'pilihan_e',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_d',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_c',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_b',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('pertanyaan', 'pilihan_a',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('gambar', 'data_gambar',
               existing_type=sa.Text(length=1500000),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
