"""image db

Revision ID: a487128f5eca
Revises: 7657caa16b02
Create Date: 2022-03-24 23:18:42.360380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a487128f5eca'
down_revision = '7657caa16b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambar',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=True),
    sa.Column('data_gambar', sa.Text(length=1500000), nullable=True),
    sa.Column('pelajaran_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pelajaran_id'], ['pelajaran.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gambar')
    # ### end Alembic commands ###
