"""add soft delete

Revision ID: c415c97d8a9e
Revises: a487128f5eca
Create Date: 2022-03-26 13:48:39.178488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c415c97d8a9e'
down_revision = 'a487128f5eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gambar', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('jadwal_ujian', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('jawaban', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('kecamatan', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('pelajaran', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('pelajaran_ujian', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('pertanyaan', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('rombongan_belajar', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('sekolah', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('ujian', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('ujian_peserta', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('ujian_sekolah', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('ujian_sekolah', 'deleted')
    op.drop_column('ujian_peserta', 'deleted')
    op.drop_column('ujian', 'deleted')
    op.drop_column('sekolah', 'deleted')
    op.drop_column('rombongan_belajar', 'deleted')
    op.drop_column('pertanyaan', 'deleted')
    op.drop_column('pelajaran_ujian', 'deleted')
    op.drop_column('pelajaran', 'deleted')
    op.drop_column('kecamatan', 'deleted')
    op.drop_column('jawaban', 'deleted')
    op.drop_column('jadwal_ujian', 'deleted')
    op.drop_column('gambar', 'deleted')
    # ### end Alembic commands ###
