"""empty message

Revision ID: f7ac547b1826
Revises: 147015822360
Create Date: 2022-03-29 10:58:08.096142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ac547b1826'
down_revision = '147015822360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latest_upload', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'latest_upload')
    # ### end Alembic commands ###
